# Generated by Django 4.2.2 on 2023-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
